#!/bin/sh
#                          
# System setup and shutdown


case "$1" in
        start)
        # buff/cache autoclean
        echo heartbeat > /sys/class/leds/status_led/trigger

        # keep cursor blink
	insmod /opt/fb_ssd1327.ko
        insmod /opt/g_ether.ko

	dhcpd usb0&
        ;;
        stop)
        printf "system shutting down ...\n"
	killall dhcpd
        rmmod g_ether
        ;;
        *)
        echo "usage: $0 {start|stop}"
        exit 1
esac

exit $?
