#!/bin/sh
#
# simulate SPI NAND as usb mass storage device
#

case "$1" in
    start)
        printf "Starting modprobe g_mass_storage: "
        modprobe g_mass_storage file=/dev/mtdblock0 removable=1 
        [ $? = 0 ] && echo "OK" || echo "FAIL"

        #echo "enable led trigger for MTD activity"
        #echo mtd > /sys/class/leds/status_led/trigger
        ;;
    stop)
        printf "Stopping modprobe g_mass_storage: "
        modprobe -r g_mass_storage
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

